
###
GET http://localhost:3000/api/tasks

###
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
"title":"R4Soft",
"description":"Trabajo freelance"
}

###
GET http://localhost:3000/api/tasks/620dcd3b4de746206432427d

// Minuto 55:40 
